version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbmodel
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
